/* -*- C++ -*- */
/* Generated by D:\opendds\OpenDDS-3.14\bin\opendds_idl version 3.14 (ACE version 6.5.12) running on input file Demo.idl */
#ifndef OPENDDS_IDL_GENERATED_DEMOTYPESUPPORTIMPL_H_BTBBBX
#define OPENDDS_IDL_GENERATED_DEMOTYPESUPPORTIMPL_H_BTBBBX
#include "DemoC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "DemoTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: DemoIdlModule */



/* Begin STRUCT: DemoTopic1 */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const DemoIdlModule::DemoTopic1& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const DemoIdlModule::DemoTopic1& stru);

bool operator>>(Serializer& strm, DemoIdlModule::DemoTopic1& stru);

size_t gen_max_marshaled_size(const DemoIdlModule::DemoTopic1& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const DemoIdlModule::DemoTopic1> stru, bool align);

void gen_find_size(KeyOnly<const DemoIdlModule::DemoTopic1> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const DemoIdlModule::DemoTopic1> stru);

bool operator>>(Serializer& strm, KeyOnly<DemoIdlModule::DemoTopic1> stru);

template <>
struct MarshalTraits<DemoIdlModule::DemoTopic1> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace DemoIdlModule {
/// This structure supports use of std::map with one or more keys.
struct  DemoTopic1_OpenDDS_KeyLessThan {
  bool operator()(const DemoIdlModule::DemoTopic1& v1, const DemoIdlModule::DemoTopic1& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.id < v2.id) return true;
    if (v2.id < v1.id) return false;
    return false;
  }
};
}


namespace DemoIdlModule {
class DemoTopic1TypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<DemoIdlModule::DemoTopic1> {
  typedef DemoIdlModule::DemoTopic1 MessageType;
  typedef DemoIdlModule::DemoTopic1Seq MessageSequenceType;
  typedef DemoIdlModule::DemoTopic1TypeSupport TypeSupportType;
  typedef DemoIdlModule::DemoTopic1TypeSupportImpl TypeSupportTypeImpl;
  typedef DemoIdlModule::DemoTopic1DataWriter DataWriterType;
  typedef DemoIdlModule::DemoTopic1DataReader DataReaderType;
  typedef DemoIdlModule::DemoTopic1_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "DemoIdlModule::DemoTopic1"; }
  static bool gen_has_key () { return true; }
  static size_t key_count () { return 1; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace DemoIdlModule {
class  DemoTopic1TypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<DemoTopic1TypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<DemoTopic1> TraitsType;
  typedef DemoTopic1TypeSupport TypeSupportType;
  typedef DemoTopic1TypeSupport::_var_type _var_type;
  typedef DemoTopic1TypeSupport::_ptr_type _ptr_type;

  DemoTopic1TypeSupportImpl() {}
  virtual ~DemoTopic1TypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static DemoTopic1TypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<DemoIdlModule::DemoTopic1>();
bool gen_skip_over(Serializer& ser, DemoIdlModule::DemoTopic1*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: DemoTopic1 */

/* End MODULE: DemoIdlModule */
#endif /* OPENDDS_IDL_GENERATED_DEMOTYPESUPPORTIMPL_H_BTBBBX */
