/* -*- C++ -*- */
/* Generated by D:\opendds\OpenDDS-3.14\bin\opendds_idl version 3.14 (ACE version 6.5.12) running on input file XData.idl */
#ifndef OPENDDS_IDL_GENERATED_XDATATYPESUPPORTIMPL_H_MGRCMB
#define OPENDDS_IDL_GENERATED_XDATATYPESUPPORTIMPL_H_MGRCMB
#include "XDataC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "XDataTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: XDataIdlModule */



/* Begin STRUCT: XDataTopic1 */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const XDataIdlModule::XDataTopic1& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const XDataIdlModule::XDataTopic1& stru);

bool operator>>(Serializer& strm, XDataIdlModule::XDataTopic1& stru);

size_t gen_max_marshaled_size(const XDataIdlModule::XDataTopic1& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const XDataIdlModule::XDataTopic1> stru, bool align);

void gen_find_size(KeyOnly<const XDataIdlModule::XDataTopic1> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const XDataIdlModule::XDataTopic1> stru);

bool operator>>(Serializer& strm, KeyOnly<XDataIdlModule::XDataTopic1> stru);

template <>
struct MarshalTraits<XDataIdlModule::XDataTopic1> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return false; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace XDataIdlModule {
/// This structure supports use of std::map with one or more keys.
struct  XDataTopic1_OpenDDS_KeyLessThan {
  bool operator()(const XDataIdlModule::XDataTopic1& v1, const XDataIdlModule::XDataTopic1& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.id < v2.id) return true;
    if (v2.id < v1.id) return false;
    return false;
  }
};
}


namespace XDataIdlModule {
class XDataTopic1TypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<XDataIdlModule::XDataTopic1> {
  typedef XDataIdlModule::XDataTopic1 MessageType;
  typedef XDataIdlModule::XDataTopic1Seq MessageSequenceType;
  typedef XDataIdlModule::XDataTopic1TypeSupport TypeSupportType;
  typedef XDataIdlModule::XDataTopic1TypeSupportImpl TypeSupportTypeImpl;
  typedef XDataIdlModule::XDataTopic1DataWriter DataWriterType;
  typedef XDataIdlModule::XDataTopic1DataReader DataReaderType;
  typedef XDataIdlModule::XDataTopic1_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "XDataIdlModule::XDataTopic1"; }
  static bool gen_has_key () { return true; }
  static size_t key_count () { return 1; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace XDataIdlModule {
class  XDataTopic1TypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<XDataTopic1TypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<XDataTopic1> TraitsType;
  typedef XDataTopic1TypeSupport TypeSupportType;
  typedef XDataTopic1TypeSupport::_var_type _var_type;
  typedef XDataTopic1TypeSupport::_ptr_type _ptr_type;

  XDataTopic1TypeSupportImpl() {}
  virtual ~XDataTopic1TypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static XDataTopic1TypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<XDataIdlModule::XDataTopic1>();
bool gen_skip_over(Serializer& ser, XDataIdlModule::XDataTopic1*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: XDataTopic1 */

/* End MODULE: XDataIdlModule */
#endif /* OPENDDS_IDL_GENERATED_XDATATYPESUPPORTIMPL_H_MGRCMB */
