// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.12
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_codegen.cpp:366


#include "XDataC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "XDataC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const XDataIdlModule::XDataTopic1 &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.id.in ()) &&
    (strm << _tao_aggregate.destination.in ()) &&
    (strm << _tao_aggregate.tTimer) &&
    (strm << _tao_aggregate.vData.in ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    XDataIdlModule::XDataTopic1 &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.id.out ()) &&
    (strm >> _tao_aggregate.destination.out ()) &&
    (strm >> _tao_aggregate.tTimer) &&
    (strm >> _tao_aggregate.vData.out ());
}

TAO_END_VERSIONED_NAMESPACE_DECL



