// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.12
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_codegen.cpp:149

#ifndef _TAO_IDL_DEMOTYPESUPPORTC_J126XL_H_
#define _TAO_IDL_DEMOTYPESUPPORTC_J126XL_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "DemoC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 12
#error This file should be regenerated with TAO_IDL
#endif

// TAO_IDL - Generated from
// D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_module\module_ch.cpp:35

namespace DemoIdlModule
{

  // TAO_IDL - Generated from
  // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:99

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DemoIdlModule::DemoTopic1, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> DemoTopic1Seq;
  

  // TAO_IDL - Generated from
  // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_interface.cpp:748

#if !defined (_DEMOIDLMODULE_DEMOTOPIC1TYPESUPPORT__VAR_OUT_CH_)
#define _DEMOIDLMODULE_DEMOTOPIC1TYPESUPPORT__VAR_OUT_CH_

  class DemoTopic1TypeSupport;
  typedef DemoTopic1TypeSupport *DemoTopic1TypeSupport_ptr;
  typedef TAO_Objref_Var_T<DemoTopic1TypeSupport> DemoTopic1TypeSupport_var;
  typedef TAO_Objref_Out_T<DemoTopic1TypeSupport> DemoTopic1TypeSupport_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:40

  class  DemoTopic1TypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_type.cpp:304

    typedef DemoTopic1TypeSupport_ptr _ptr_type;
    typedef DemoTopic1TypeSupport_var _var_type;
    typedef DemoTopic1TypeSupport_out _out_type;

    // The static operations.
    static DemoTopic1TypeSupport_ptr _duplicate (DemoTopic1TypeSupport_ptr obj);

    static void _tao_release (DemoTopic1TypeSupport_ptr obj);

    static DemoTopic1TypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static DemoTopic1TypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DemoTopic1TypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DemoTopic1TypeSupport (void);

    

    virtual ~DemoTopic1TypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1TypeSupport (const DemoTopic1TypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1TypeSupport (DemoTopic1TypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1TypeSupport &operator= (const DemoTopic1TypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1TypeSupport &operator= (DemoTopic1TypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_interface.cpp:748

#if !defined (_DEMOIDLMODULE_DEMOTOPIC1DATAWRITER__VAR_OUT_CH_)
#define _DEMOIDLMODULE_DEMOTOPIC1DATAWRITER__VAR_OUT_CH_

  class DemoTopic1DataWriter;
  typedef DemoTopic1DataWriter *DemoTopic1DataWriter_ptr;
  typedef TAO_Objref_Var_T<DemoTopic1DataWriter> DemoTopic1DataWriter_var;
  typedef TAO_Objref_Out_T<DemoTopic1DataWriter> DemoTopic1DataWriter_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:40

  class  DemoTopic1DataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_type.cpp:304

    typedef DemoTopic1DataWriter_ptr _ptr_type;
    typedef DemoTopic1DataWriter_var _var_type;
    typedef DemoTopic1DataWriter_out _out_type;

    // The static operations.
    static DemoTopic1DataWriter_ptr _duplicate (DemoTopic1DataWriter_ptr obj);

    static void _tao_release (DemoTopic1DataWriter_ptr obj);

    static DemoTopic1DataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static DemoTopic1DataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DemoTopic1DataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DemoIdlModule::DemoTopic1 & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DemoIdlModule::DemoTopic1 & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DemoIdlModule::DemoTopic1 & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DemoIdlModule::DemoTopic1 & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DemoIdlModule::DemoTopic1 & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DemoIdlModule::DemoTopic1 & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DemoIdlModule::DemoTopic1 & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DemoIdlModule::DemoTopic1 & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DemoIdlModule::DemoTopic1 & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DemoIdlModule::DemoTopic1 & instance_data) = 0;

    // TAO_IDL - Generated from
    // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DemoTopic1DataWriter (void);

    

    virtual ~DemoTopic1DataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1DataWriter (const DemoTopic1DataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1DataWriter (DemoTopic1DataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1DataWriter &operator= (const DemoTopic1DataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1DataWriter &operator= (DemoTopic1DataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_interface.cpp:748

#if !defined (_DEMOIDLMODULE_DEMOTOPIC1DATAREADER__VAR_OUT_CH_)
#define _DEMOIDLMODULE_DEMOTOPIC1DATAREADER__VAR_OUT_CH_

  class DemoTopic1DataReader;
  typedef DemoTopic1DataReader *DemoTopic1DataReader_ptr;
  typedef TAO_Objref_Var_T<DemoTopic1DataReader> DemoTopic1DataReader_var;
  typedef TAO_Objref_Out_T<DemoTopic1DataReader> DemoTopic1DataReader_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:40

  class  DemoTopic1DataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_type.cpp:304

    typedef DemoTopic1DataReader_ptr _ptr_type;
    typedef DemoTopic1DataReader_var _var_type;
    typedef DemoTopic1DataReader_out _out_type;

    // The static operations.
    static DemoTopic1DataReader_ptr _duplicate (DemoTopic1DataReader_ptr obj);

    static void _tao_release (DemoTopic1DataReader_ptr obj);

    static DemoTopic1DataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static DemoTopic1DataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DemoTopic1DataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DemoIdlModule::DemoTopic1Seq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DemoIdlModule::DemoTopic1Seq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DemoIdlModule::DemoTopic1 & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DemoIdlModule::DemoTopic1 & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DemoIdlModule::DemoTopic1Seq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DemoIdlModule::DemoTopic1Seq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DemoIdlModule::DemoTopic1Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DemoIdlModule::DemoTopic1 & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DemoIdlModule::DemoTopic1 & instance_data) = 0;

    // TAO_IDL - Generated from
    // D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DemoTopic1DataReader (void);

    

    virtual ~DemoTopic1DataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1DataReader (const DemoTopic1DataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1DataReader (DemoTopic1DataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1DataReader &operator= (const DemoTopic1DataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (DemoTopic1DataReader &operator= (DemoTopic1DataReader &&))
#endif /* ACE_HAS_CPP11 */
  };

// TAO_IDL - Generated from
// D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_module\module_ch.cpp:64

} // module DemoIdlModule

// TAO_IDL - Generated from
// D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DEMOIDLMODULE_DEMOTOPIC1TYPESUPPORT__TRAITS_)
#define _DEMOIDLMODULE_DEMOTOPIC1TYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::DemoIdlModule::DemoTopic1TypeSupport>
  {
    static ::DemoIdlModule::DemoTopic1TypeSupport_ptr duplicate (
        ::DemoIdlModule::DemoTopic1TypeSupport_ptr p);
    static void release (
        ::DemoIdlModule::DemoTopic1TypeSupport_ptr p);
    static ::DemoIdlModule::DemoTopic1TypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DemoIdlModule::DemoTopic1TypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DEMOIDLMODULE_DEMOTOPIC1DATAWRITER__TRAITS_)
#define _DEMOIDLMODULE_DEMOTOPIC1DATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::DemoIdlModule::DemoTopic1DataWriter>
  {
    static ::DemoIdlModule::DemoTopic1DataWriter_ptr duplicate (
        ::DemoIdlModule::DemoTopic1DataWriter_ptr p);
    static void release (
        ::DemoIdlModule::DemoTopic1DataWriter_ptr p);
    static ::DemoIdlModule::DemoTopic1DataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DemoIdlModule::DemoTopic1DataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DEMOIDLMODULE_DEMOTOPIC1DATAREADER__TRAITS_)
#define _DEMOIDLMODULE_DEMOTOPIC1DATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::DemoIdlModule::DemoTopic1DataReader>
  {
    static ::DemoIdlModule::DemoTopic1DataReader_ptr duplicate (
        ::DemoIdlModule::DemoTopic1DataReader_ptr p);
    static void release (
        ::DemoIdlModule::DemoTopic1DataReader_ptr p);
    static ::DemoIdlModule::DemoTopic1DataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DemoIdlModule::DemoTopic1DataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// D:\opendds\ACE_wrappers\TAO\TAO_IDL\be\be_codegen.cpp:1686
#if defined (__ACE_INLINE__)
#include "DemoTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

